config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  root 'users#new'
  get 'sessions/new'

  resources :users
  resources :statuses
  resources :likes
  resource :session

  get 'likes/new'

  get 'likes/create'

  get 'likes/edit'

  get 'likes/update'

  get 'likes/delete'

  get 'statuses/new'

  get 'statuses/create'

  get 'statuses/edit'

  get 'statuses/update'

  get 'statuses/delete'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'

end

app/models/like.rb
class Like < ActiveRecord::Base
  validates :user_id, presence: true
  validates :status_id, presence: true

  belongs_to :user
  belongs_to :status
end

app/models/status.rb
class Status < ActiveRecord::Base

  validates :title, presence: true, length: { :minimum => 8, :too_short => "title is too short"}
  validates :content, presence: true, length: { :minimum => 10, :too_short => "content is too short"}

  belongs_to :user
  has_many :likes, :dependent => :destroy

  #makes the defaule ordering of status by created_at
  default_scope { order(created_at: :desc) }


end

app/models/user.rb
class User < ActiveRecord::Base

  validates :name, presence: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
             format: {with: VALID_EMAIL_REGEX}, 
             uniqueness: true

  has_secure_password

  validates :password, presence: true, length: { in: 6..20 }, allow_nil: true
  validates :password_confirmation, presence: true

  has_many :statuses, :dependent => :destroy
  has_many :likes, :dependent => :destroy


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new
  end

  def create
    @status = Status.find(params[:like][:status])

    if !Like.find_by(status_id: params[:like][:status])
      @like = Like.new(status_id: params[:like][:status], user_id: params[:like][:user])
      if @like.save
        flash[:notice] = "You liked #{@status.title}!"
        redirect_to root_path
      else
        redirect_to root_path
      end
    else
      flash[:alert] = "You liked before!"
      redirect_to root_path
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @like = Like.find(params[:id])
    @like.destroy
    flash[:notice] = "You unlike."
    redirect_to status_path(@like.status_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      flash.now[:notice] = 'Welcome, '+user.email+"!"
      redirect_to statuses_path
    else
      flash.now[:alert] = 'Please log in again'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  
  def index
    @statuses = Status.order('created_at')
  end

  def show
    @status = Status.find(params[:id])
  end

  def new
    if logged_in?
      @status = Status.new
    else
      redirect_to login_path
    end
  end

  def create
    if logged_in?
      @status = Status.new(status_params)
      if @status.save
        flash[:notice] = "Status is created successfully."
        redirect_to @status
      else
        flash[:alert] = "Error creating status."
        render "new"
      end
    else
      redirect_to login_path
    end
  end


  def edit
    @status = Status.find(params[:id])
  end

  def update
    @status = Status.find(params[:id])

    if logged_in?
      if @status.update_attributes(status_params)
        flash[:notice] = "Status is updated successfully."
        redirect_to @status
      else
        render "edit"
      end
    else
      redirect_to login_path
    end
  end

  def destroy
    Status.find(params[:id]).destroy
    flash[:notice] = "Status is deleted."
    redirect_to statuses_path
  end

  private

    def status_params
      params.require(:status).permit(:title, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :logged_in_user, only: [:edit]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Account created. Please log in now."
      redirect_to @user
    else
      flash[:alert] = "Error creating account: "
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
  end


  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:notice] = "Account is updated successfully."
      redirect_to @user
    else
      render "edit"
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:notice] = "Account is deleted"
    redirect_to statuses_path
  end


  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do 
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message 
            end)
    end
    nil
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testing</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    
  <%= flash_messages %>

  <%= yield %>

  </body>
</html>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/likes/delete.html.erb
<h1>Likes#delete</h1>
<p>Find me in app/views/likes/delete.html.erb</p>

app/views/likes/edit.html.erb
<h1>Likes#edit</h1>
<p>Find me in app/views/likes/edit.html.erb</p>

app/views/likes/new.html.erb
<h1>Likes#new</h1>
<p>Find me in app/views/likes/new.html.erb</p>

app/views/likes/update.html.erb
<h1>Likes#update</h1>
<p>Find me in app/views/likes/update.html.erb</p>

app/views/statuses/create.html.erb
<h1>Statuses#create</h1>
<p>Find me in app/views/statuses/create.html.erb</p>

app/views/statuses/delete.html.erb
<h1>Statuses#delete</h1>
<p>Find me in app/views/statuses/delete.html.erb</p>

app/views/statuses/edit.html.erb
<h1>Statuses#edit</h1>
<p>Find me in app/views/statuses/edit.html.erb</p>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@status) do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :content %>
      <%= f.text_field :content, class: 'form-control' %>

      <%= f.submit "Update Status", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/statuses/index.html.erb
test
  

app/views/statuses/new.html.erb
<h1>Statuses#new</h1>
<p>Find me in app/views/statuses/new.html.erb</p>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@status) do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :content %>
      <%= f.text_field :content, class: 'form-control' %>

      <%= f.submit "Update Status", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/statuses/show.html.erb
<div>
  <%= @status.title %>
  <%= @status.content %>
</div>

<%= link_to "delete", @status, method: :delete,
                                data: {confirm: "You sure?"} %>

app/views/statuses/update.html.erb
<h1>Statuses#update</h1>
<p>Find me in app/views/statuses/update.html.erb</p>

app/views/users/edit.html.erb
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
                <li>
                <%= link_to "Log Out", signout_path, method: :delete %>
                </li>

        <% else %>
        <li><%= link_to "Log In", new_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>